version: '3'
services: 
    scraping:
        image: jorgelba/node-puppeteer
        volumes: 
            - ./scraping:/scraping
        command: bash -c "cd /scraping && npm i" # && npm start
    DB:
        image: mongo:3.6
        ports: 
          - 27017:27017
        volumes: 
          # Altere o caminho do volume para uma pasta existente.
          # Caso não queira salvar os dados remova todas as linhas do volumes.
          - /media/jorge/rahmai/omegacom/softwares/volumes:/data/db
    queue:
      image: node:12.18.3
      volumes:
        - ./queue:/queue
      command: bash -c "cd /queue && npm i"
    redis:
      image: redis:6-alpine
      ports: 
        - 6379:6379