version: '3'
services: 
    worker:
        image: jorgelba/node-puppeteer
        volumes: 
          - .:/worker
        command: bash -c "cd /worker && npm i && npm start"
        network_mode: host